-- Add research consent to profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS research_consent boolean DEFAULT false;

COMMENT ON COLUMN public.profiles.research_consent IS 'User consent for their anonymized data to be used for research studies.';

-- Create feedback table for satisfaction metrics
CREATE TABLE IF NOT EXISTS public.feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES public.profiles(id) NOT NULL,
    target_type text NOT NULL CHECK (target_type IN ('chat_session', 'exercise', 'general', 'feature')),
    target_id text, -- Flexible reference to chat_session_id or exercise_id
    rating integer CHECK (rating >= 1 AND rating <= 5),
    comment text,
    created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on feedback
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;

-- Policy: Users can create their own feedback
CREATE POLICY "Users can insert their own feedback" 
ON public.feedback FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can view their own feedback
CREATE POLICY "Users can view their own feedback" 
ON public.feedback FOR SELECT 
USING (auth.uid() = user_id);


-- Create Anonymized View for Research: Daily Check-ins (Mood)
CREATE OR REPLACE VIEW public.analytics_anonymized_moods AS
SELECT 
    p.institution_id,
    p.career_program,
    p.semester,
    dc.mood_score,
    dc.mood_label,
    dc.created_at,
    dc.feelings
FROM 
    public.daily_checkins dc
JOIN 
    public.profiles p ON dc.user_id = p.id
WHERE 
    p.research_consent = true; -- Only include consented users

-- Create Anonymized View for Research: Exercise Effectiveness
CREATE OR REPLACE VIEW public.analytics_anonymized_exercises AS
SELECT 
    p.institution_id,
    p.career_program,
    p.semester,
    re.exercise_type,
    re.duration_seconds,
    re.pre_mood_score,
    re.post_mood_score,
    (re.post_mood_score - re.pre_mood_score) as mood_improvement,
    re.completed_at
FROM 
    public.relaxation_exercises re
JOIN 
    public.profiles p ON re.user_id = p.id
WHERE 
    p.research_consent = true;

-- Create Anonymized View for Research: Chat Usage patterns
CREATE OR REPLACE VIEW public.analytics_anonymized_chat_usage AS
SELECT 
    p.institution_id,
    p.career_program,
    p.semester,
    cs.created_at as session_date,
    count(cm.id) as message_count,
    MAX(CASE WHEN cm.sender = 'user' THEN 1 ELSE 0 END) as has_user_interaction
FROM 
    public.chat_sessions cs
JOIN 
    public.profiles p ON cs.user_id = p.id
LEFT JOIN
    public.chat_messages cm ON cs.id = cm.session_id
WHERE 
    p.research_consent = true
GROUP BY
    cs.id, p.institution_id, p.career_program, p.semester, cs.created_at;
